# Generated by Django 2.1.2 on 2018-10-16 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='mood',
            field=models.CharField(choices=[('h', 'Happy'), ('s', 'Sad'), ('p', 'Sleepy'), ('e', 'Emotional')], default='h', max_length=1),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='songs',
            field=models.ManyToManyField(blank=True, to='main_app.Song'),
        ),
    ]
